title: Ticketz PRO Docs
description: Multilingual documentation for Ticketz PRO integrations, setup, and billing guides.
baseurl: ""
url: "https://doc.ticketz.pro"
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
defaults:
  - scope:
      path: ""
    values:
      layout: default
